### PR TITLE
Fixing breakpoints for VSCode

### PR DESCRIPTION
**Pull request by igor-ribeiiro**
Allow breakpoints set in the TypeScript source to bind and break when debugging custom functions.

Fixes https://github.com/OfficeDev/Excel-Custom-Functions/issues/236

### CODE REVIEW

**Comment by akrantz** [comment]
So ultimately, it looks like just removing "outFiles" was sufficient to get it working.

**Comment by igor-ribeiiro** [comment]
> So ultimately, it looks like just removing "outFiles" was sufficient to get it working.

Yeah, it was the simpler way to get it working and probably the most correct.

**Review by akrantz — APPROVED** [review]

**Comment by TCourtneyOwen** [comment]
Was this a result of a bad merge in the past (i.e.. did we perhaps accidentally updated launch.json)?I am just curious why this stopped working at some point

**Review by TCourtneyOwen — APPROVED** [review]

**Comment by igor-ribeiiro** [comment]
> Was this a result of a bad merge in the past (i.e.. did we perhaps accidentally updated launch.json)?I am just curious why this stopped working at some point

I don't think it was a mistake. I think @akrantz added it in the past when the files were sent to the dist folder (might have been needed). 
But the we are supposing the VSCode updated in a way that this line wasn't needed anymore and would actually break the debugger.

**Pull request merged**
