### PR TITLE
Merge changes from Office-Addin-TaskPane

### PR DESCRIPTION
**Pull request by akrantz**

### CODE REVIEW

**Comment by TCourtneyOwen** [comment]
Did you check to ensure the project works with the merge? Once we have the updated versions of office-addin-scripts published, we can get the UI tests running for this repo and won't have to validate manually

**Comment by akrantz** [comment]
Yes, I verified that the project works, both task pane and custom functions.

**Comment by TCourtneyOwen** [comment]
I see the Mac build is taking a very long time. I don’t have the recent Mac agent builds handy, but I think we’ve had jobs pass on the Mac Mini I recently set up so it may be something with the agent machine or an issue with the project building on Mac. We should investigate if the build job doesn’t finish soon

**Comment by akrantz** [comment]
I see that too. These projects all build OK on my mac.

**Comment by TCourtneyOwen** [comment]
The reason the build stalls on Mac is because of the office-certs prompt

**Comment by TCourtneyOwen** [comment]
Once I install the certs and then rerun the job, the install/build/test phases pass on Mac

**Pull request merged**
