### PR TITLE
Updating packages

### PR DESCRIPTION
**Pull request by igor-ribeiiro**
This PR is very similar to [https://github.com/OfficeDev/Excel-Custom-Functions/pull/271](https://github.com/OfficeDev/Excel-Custom-Functions/pull/271) with just one change:
npm audit fix was not ran on office-addin-debugging updated package. Turns out the latest debugging package is also not compatible with CF tests.

### CODE REVIEW

**Comment by akrantz** [comment]
@igor-ribeiiro Not sure what's going on but your comments seem suspicious. There is nothing wrong with office-addin-debugging in terms of NPM. I think you need to be more clear about why custom functions tests are not working. I was thinking the issue with the latest custom-functions-metadata-plugin might be related to webpack 4 versus 5. You might want to remove your local node_modules folder and then do "npm install" to make sure that you're not running into local issues with the npm packages.

**Comment by igor-ribeiiro** [comment]
> debugging

I'm not sure why it is giving problems sometimes as well. I don't know all the consequences of running `npm run audit`, but it does seem to sometimes give lock json changes that can't be fixed by simply deleting node_modules or clonning the project again.

**Comment by igor-ribeiiro** [comment]
> @igor-ribeiiro Not sure what's going on but your comments seem suspicious. There is nothing wrong with office-addin-debugging in terms of NPM. I think you need to be more clear about why custom functions tests are not working. I was thinking the issue with the latest custom-functions-metadata-plugin might be related to webpack 4 versus 5. You might want to remove your local node_modules folder and then do "npm install" to make sure that you're not running into local issues with the npm packages.

The custom-functions-metadata-plugin was a problem and I'm not adding it anymore. The office-addin-debugging is gicing some other problem that the tests fail as well.
I really didn't dive that deep on why, I just wanted the updates that are possible to be merged to fix the vulnerabilities ASAP.

**Comment by akrantz** [comment]
package.json contains dependencies and their versions, and package-lock.json captures the actual versions of the dependency tree. When you run "npm audit fix", it may find that it can update package-lock.json so that it uses a different version of the dependency while still meeting semver requirements for the dependencies.

When you change branches or pull new updates, you cannot merge the package-lock.json file. If you delete it and then run "npm install" it will generate a new one using the latest versions of the dependencies. 

Without doing the "npm audit fix", can you get to a point that things work?

**Pull request merged**
