### PR TITLE
CustomFunctions.associate() calls added automatically

### PR DESCRIPTION
**Pull request by akrantz**
The custom-functions-metadata-plugin will automatically write the required CustomFunctions.associate("ID", func) calls into the bundle so the developer does not have to remember to add them.

### CODE REVIEW

**Comment by akrantz** [comment]
@Zlatkovsky The Excel-Custom-Functions template no longer requires explicit CustomFunctions.associate() calls. Great for copy code snippets from ScriptLab.

**Comment by Zlatkovsky** [comment]
@akrantz :  sweet!

**Comment by akrantz** [comment]
@TCourtneyOwen Please review. Thanks.

**Comment by akrantz** [comment]
Also, these changes should make it easier to provide unit testing of the code because there is no direct calls to CustomFunctions.associate() anymore.

**Pull request merged**
