### PR TITLE
Merge-office-addin-taskpane/master

### PR DESCRIPTION
**Pull request by TCourtneyOwen**

### CODE REVIEW

**Comment by TCourtneyOwen** [comment]
something is causing build to fail in the CI loop. Investigating

**Comment by TCourtneyOwen** [comment]
Looks like the update to clean-webpack-plugin causes the build failure. Reverting to previous version

**Comment by TCourtneyOwen** [comment]
Test phase for Mac, which was previously disabled, fails. Investigating, but I don't think we should hold up the PR for that

**Comment by TCourtneyOwen** [comment]
Job now passes: https://office.visualstudio.com/OC/_build/results?buildId=2570781

**Comment by akrantz** [comment]
> Looks like the update to clean-webpack-plugin causes the build failure. Reverting to previous version

Yes, because Excel-Custom-Functions has the dev-server to serve the files out of dist folder generated from the separate build, the CleanWebpackPlugin change causes an issue. Ultimately, we need a way to have webpack dev server be able to serve up files which don't have web browser reload logic which won't work in custom functions runtime which is a JavaScript only environment and not a webbrowser. I never found a good solution which is why we have this workaround which is less than ideal.

**Comment by akrantz** [comment]
@TCourtneyOwen I did Retry on the CI build...

**Pull request merged**
