### PR TITLE
Shared template

### PR DESCRIPTION
**Pull request by igor-ribeiiro**
The shared template we had a branch for is not working for custom functions (the task pane part works).
Instead of keep trying to make the old branch work, I just started from master and followed the tutorial:
[Shared App](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/configure-your-add-in-to-use-a-shared-runtime#:~:text=1%20Create%20the%20add-in%20project.%20If%20you%20are,Configure%20the%20webpack.config.js%20file.%20The%20webpack.config.js...%20More%20)
and it worked right away.

These changes are a simple merge to master and then apply the tutorial changes, which makes the shared runtime work.

### CODE REVIEW

**Comment by akrantz** [comment]
You could just rebase this off master rather than have all the commits to merge. When on this branch, run `git rebase master`. If you have any issues, you can always abort using `git rebase --abort`. Reach out if you have questions.

**Comment by igor-ribeiiro** [comment]
> You could just rebase this off master rather than have all the commits to merge. When on this branch, run `git rebase master`. If you have any issues, you can always abort using `git rebase --abort`. Reach out if you have questions.

Thanks, I could rebase but I'm now thinking that the main problem is that this shared runtime branch is so outdated that it is not easy to make it work and it would be better to simply remove it and create a new one.

@millerds the process I'm doing is simply going to `master` and following the tutorial I mentioned in the description to make the app "shared". 
The changes are pretty minimal, but if I put to merge with the old shared branch then all these changes are created, which I do not want.

Do you have any suggestions on how to proceed? I can make so the `shared` branches are equal to master, but that would involve losing the previous commits made to it. The different commits are mostly a bunch of merges we previously did and I think that might have broken some behavior

**Comment by millerds** [comment]
I think we should start by merging the changes from master into the branch and then see how the branch is after that.

You should be able to use the instructions you followed on top of master to check if things are right in the branch.  There may be some other changes in the branch that are desirable that aren't part of the documentation.

**Comment by igor-ribeiiro** [comment]
As you will want to know why the bug is happening, I will keep trying to figure it out for now

**Pull request closed without merging**
