### PR TITLE
Allow for customization of manifest

### PR DESCRIPTION
**Pull request by TCourtneyOwen**
I have locally updated the Yo Office code locally to be able to customize the guid and display name for custom functions, just as do for the other Yo Office project templates. Once this change is approved, and my Yo Office change is approved, I will psuh this change to the Typescript and master branches as well

### CODE REVIEW

**Comment by akrantz** [comment]
If we do this, then we cannot just run the templates as they are. That's why I wanted to update to have `office-addin-manifest personalize manifest.xml --guid --name MyName`. I think it would be fairly easy to add that and provide a more useful experience. Yo Office could call that after running npm install.

**Comment by TCourtneyOwen** [comment]
so the concern here is that this will break things for people who just clone the repo instead of going through Yo Offfce?

**Comment by akrantz** [comment]
Yes

**Comment by TCourtneyOwen** [comment]
OK, I think I am fine with that plan. I can largely just take the code I have added in Yo Office for customizing the manifest and add it to office-addin-manifest.  I was trying to access the repo for the office-addin-manifest project using the link off NPM and it seems to be dead:  https://github.com/OfficeDev/Office-Addin-Scripts.  Is this not a valid location anymore?

**Comment by akrantz** [comment]
It's valid.

**Comment by akrantz** [comment]
This can be closed since you're doing the work to use `office-addin-manfest personalize` to update the manifest.

**Pull request closed without merging**
