### PR TITLE
Merge office addin taskpane

### PR DESCRIPTION
**Pull request by TCourtneyOwen**

### CODE REVIEW

**Comment by TCourtneyOwen** [comment]
Need to investigate build failure I am not hitting locally

**Comment by akrantz** [comment]
@TCourtneyOwen  I will merge once the checks complete. As a reminder, be sure to use "Merge pull requests" and not squash the merges between the templates.

**Comment by akrantz** [comment]
@TCourtneyOwen  It says that this branch is out of date with master. Did you get the latest from this repository before doing the merge?

**Comment by TCourtneyOwen** [comment]
I pulled in the latest changes - not sure why it's saying that.  This PR actually contains two merges from Office-Addin-Taskpane - one from earlier when I opened the PR and one just now. Maybe that's the confusion

**Comment by TCourtneyOwen** [comment]
Oh I see maybe someone updated ECF master in  the last day or so

**Comment by akrantz** [comment]
Right, you need to go back to master, pull the latest changes, make a new branch, do the merge, etc. You don't want to start with the earlier branch.

**Comment by TCourtneyOwen** [comment]
Just merged latest from master and pushed changes.

**Pull request merged**
