### PR TITLE
Combine e2e test files

### PR DESCRIPTION
**Pull request by millerds**
The order of the e2e test made it so that the webview setting was erased before the UI tests were run.  To fix this I combined the debugger tests in one file with the UI tests so I can control the order of the tests.  I also logged out the user agent to be able to check that with the pipeline runs for each webview (don't have a way to automatically test this yet since the tests don't know which web view is expected).

### CODE REVIEW

**Comment by igor-ribeiiro** [comment]
Test still aren't passing D:
So what is about the order?
Do the UI tests have to be executed before the debugger tests and before we could not enforce that?

**Comment by millerds** [comment]
The tests in the master branch were passing in the lab before this change.  

When trying to figure out the shared runtime test problems I discovered that by adding the debugger test the setting to use a certain webview was cleaned up before the UI test were run . . . so essentially the pipeline tests were all running on the default webview rather than the one set by the pipeline.  By combining the tests into one file I can make the debugger run after the UI tests so that the UI tests have the webview setting.  Apparently, this is making the debugger test fail in the lab (the UI tests are passing).

**Comment by igor-ribeiiro** [comment]
> The tests in the master branch were passing in the lab before this change.
> 
> When trying to figure out the shared runtime test problems I discovered that by adding the debugger test the setting to use a certain webview was cleaned up before the UI test were run . . . so essentially the pipeline tests were all running on the default webview rather than the one set by the pipeline. By combining the tests into one file I can make the debugger run after the UI tests so that the UI tests have the webview setting. Apparently, this is making the debugger test fail in the lab (the UI tests are passing).

I remember that the tests always open a new instance of the client, so they "should" always have a fresh setup.
Given that now the debugging tests are failing when put to execute later, we can see that the order is mattering when it shouldn't.
Is there any way, maybe using `office-addin-dev-setting` to "clear" this cache and ensure both tests run in a clean fresh environment? The order really shouldn't matter.

**Comment by millerds** [comment]
> 

It's not about the fresh session of the client application that required the change.  office-addin-dev-settings allows us to setup some properties (stored in the registry) used when running npm start.  One of those is the webview setting that allows us to pick between ie, edge-legacy, and edge-chromium.  Those setting get cleared out when running "npm stop"  The debugging tests and the UI test each start and stop the dev server when running those tests, but the command to choose the webview is outside of the tests ('office-addin-dev-settings webview . . .' is run from the commandline).  That shouldn't have an effect on the debug tests since it would get cleared out at the end of the UI tests.

**Comment by igor-ribeiiro** [comment]
> > 
> 
> It's not about the fresh session of the client application that required the change. office-addin-dev-settings allows us to setup some properties (stored in the registry) used when running npm start. One of those is the webview setting that allows us to pick between ie, edge-legacy, and edge-chromium. Those setting get cleared out when running "npm stop" The debugging tests and the UI test each start and stop the dev server when running those tests, but the command to choose the webview is outside of the tests ('office-addin-dev-settings webview . . .' is run from the commandline). That shouldn't have an effect on the debug tests since it would get cleared out at the end of the UI tests.

Is there a way to run this `office-addin-dev-setting` inside the test code? On some sort of API?
Then we could run it again between both tests

**Comment by millerds** [comment]
> > > 
> > 
> > 
> > It's not about the fresh session of the client application that required the change. office-addin-dev-settings allows us to setup some properties (stored in the registry) used when running npm start. One of those is the webview setting that allows us to pick between ie, edge-legacy, and edge-chromium. Those setting get cleared out when running "npm stop" The debugging tests and the UI test each start and stop the dev server when running those tests, but the command to choose the webview is outside of the tests ('office-addin-dev-settings webview . . .' is run from the commandline). That shouldn't have an effect on the debug tests since it would get cleared out at the end of the UI tests.
> 
> Is there a way to run this `office-addin-dev-setting` inside the test code? On some sort of API? Then we could run it again between both tests

There probably is, but then you are creating separate tests for each webview (because you have to set it differently) and run 9 things all the time instead of 3.  Putting it in the pipeline make it parameterized.  Not sure if there is a way to make mocha test call parameterized which would allow us other options.  The bottom line is we need to be able to run the tests without make it complicated to maintain.

**Review by igor-ribeiiro — APPROVED** [review]

**Pull request merged**
