### PR TITLE
Updating custom-functions-plugin package version

### PR DESCRIPTION
**Pull request by igor-ribeiiro**
Using the last version of ```custom-functions-metadata-plugin``` that was just published.

Tests:
npm run test

### CODE REVIEW

**Comment by akrantz** [comment]
This change is not really neccessary. There are no actual changes to this plugin between these two version.

**Comment by akrantz** [comment]
Well this does change package-lock.json to use lockfile version 2 with NPM v7. Is this also a desired change?

**Comment by igor-ribeiiro** [comment]
Maybe it's a not-needed change, I just update it for the custom-functions bug. Maybe we can close this PR them?
Shouldn't I always commit the .lock file? I don't look into it usually

**Comment by akrantz** [comment]
This PR is not required.

**Pull request closed without merging**
