### PR TITLE
add launch config for debugging custom functions

### PR DESCRIPTION
**Pull request by akrantz**

### CODE REVIEW

**Review by millerds — APPROVED** [review]

**Comment by TCourtneyOwen** [comment]
Does this actually allow for debugging CFs? I haven't been able to get that to work lately, but if you have, that's great!

**Comment by akrantz** [comment]
Sort of.  As has always been the case, this uses the /dist folder in the manifest so you need to do `npm run build` first to populate /dist.  I was able to launch Excel and I see the ChakraCore instance is created with debugging enabled. `http://localhost:9229/json` will show this. Also, the VS Code debugger will attach. 

I could not hit a breakpoint, but I could click the || break icon, and upon executing a custom function, it will break in the foundation.bundle.  If you single step, it will call into the udf-host.bundle. However, I couldn't see how this calls into the functions.js code. 

I do see that the `https://localhost:3000/dist/functions.js` file is downloaded into the WEF cache.

Going to:
`C:\Users\{username}\AppData\Local\Microsoft\Office\16.0\Wef\CustomFunctions\v1.7\Registry\{base64 value}\{add-in id}` folder will show `javascript.js.link` and `metadata.json.link` whose contents point to the `functions.js` and `functions.json` files respectively.

The functions.js file is actually named bundle.js -- this might be one source of problems -- but the last line does point to the `functions.js.map` file which is downloaded and in the same folder, so mapping back to the TypeScript source should work.

There's more to investigate about why breakpoints don't work, but it's not that far off.

**Comment by akrantz** [comment]
@TCourtneyOwen Why are tests not run for Windows 1803?  I think the tests for Windows 1904 failed because it doesn't do an "npm run build" to populate /dist before the test. I can't remember if this ever worked.

**Comment by TCourtneyOwen** [comment]
@akrantz I honestly can't remember why we deactivated the test phase for 1809, but I will reenable

**Comment by TCourtneyOwen** [comment]
@akrantz Test phase reenabled on 1809 agent pool

**Comment by akrantz** [comment]
@TCourtneyOwen The test seems flaky. This change doesn't change any executable code, so it is really safe to merge anyway.

**Comment by akrantz** [comment]
Well, re-running the job allowed it to pass.

**Pull request merged**
